apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-db-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-db-app
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-db-app
    spec:
      volumes:
        - name: config-pv-volume
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: db-schema-volume
          configMap:
            name: db-schema-init
        - name: db-config-volume
          configMap:
            name: db-lowercase-config
      containers:
      - name: {{ .Values.appName }}-db-image
        image: postgres
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: db-schema-volume
          mountPath: /docker-entrypoint-initdb.d/schema.sql
          subPath: schema.sql
        - name: config-pv-volume
          mountPath: "/var/lib/postgresql/data"
