apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schema-init
  namespace: {{ .Values.namespace }}
data:
  schema.sql: |
    CREATE DATABASE "{{ .Values.databaseName }}";
    \c {{ .Values.databaseName }}
    CREATE TABLE "learner" (
      "id_learner" int PRIMARY KEY,
      "first_name" varchar,
      "last_name" varchar
    );
    \c {{ .Values.databaseName }}
    INSERT INTO "learner"(id_learner, first_name, last_name) VALUES ('01', 'Jose', 'Navarro');
    INSERT INTO "learner"(id_learner, first_name, last_name) VALUES ('02', 'Edgar', 'Aceves');

